<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert(['name_ru' => 'Австралия', 'name_eng' => 'Australia']);
        DB::table('countries')->insert(['name_ru' => 'Австрия', 'name_eng' => 'Austria']);
        DB::table('countries')->insert(['name_ru' => 'Азербайджан', 'name_eng' => 'Azerbaijan']);
        DB::table('countries')->insert(['name_ru' => 'Албания', 'name_eng' => 'Albania']);
        DB::table('countries')->insert(['name_ru' => 'Алжир', 'name_eng' => 'Algeria']);
        DB::table('countries')->insert(['name_ru' => 'Американские Виргинские острова', 'name_eng' => 'American Virgin Islands']);
        DB::table('countries')->insert(['name_ru' => 'Ангилья', 'name_eng' => 'Anguilla']);
        DB::table('countries')->insert(['name_ru' => 'Ангола', 'name_eng' => 'Angola']);
        DB::table('countries')->insert(['name_ru' => 'Андорра', 'name_eng' => 'Andorra']);
        DB::table('countries')->insert(['name_ru' => 'Антигуа и Барбуда', 'name_eng' => 'Antigua and Barbuda']);
        DB::table('countries')->insert(['name_ru' => 'Аргентина', 'name_eng' => 'Argentina']);
        DB::table('countries')->insert(['name_ru' => 'Армения', 'name_eng' => 'Armenia']);
        DB::table('countries')->insert(['name_ru' => 'Аруба', 'name_eng' => 'Aruba']);
        DB::table('countries')->insert(['name_ru' => 'Афганистан', 'name_eng' => 'Afghanistan']);
        DB::table('countries')->insert(['name_ru' => 'Багамские острова', 'name_eng' => 'Bahamas']);
        DB::table('countries')->insert(['name_ru' => 'Бангладеш', 'name_eng' => 'Bangladesh']);
        DB::table('countries')->insert(['name_ru' => 'Барбадос', 'name_eng' => 'Barbados']);
        DB::table('countries')->insert(['name_ru' => 'Бахрейн', 'name_eng' => 'Bahrain']);
        DB::table('countries')->insert(['name_ru' => 'Беларусь', 'name_eng' => 'Belarus']);
        DB::table('countries')->insert(['name_ru' => 'Белиз', 'name_eng' => 'Belize']);
        DB::table('countries')->insert(['name_ru' => 'Бельгия', 'name_eng' => 'Belgium']);
        DB::table('countries')->insert(['name_ru' => 'Бенин', 'name_eng' => 'Benin']);
        DB::table('countries')->insert(['name_ru' => 'Бермудские Острова', 'name_eng' => 'Bermuda']);
        DB::table('countries')->insert(['name_ru' => 'Болгария', 'name_eng' => 'Bulgaria']);
        DB::table('countries')->insert(['name_ru' => 'Боливия', 'name_eng' => 'Bolivia']);
        DB::table('countries')->insert(['name_ru' => 'Босния и Герцеговина', 'name_eng' => 'Bosnia and Herzegovina']);
        DB::table('countries')->insert(['name_ru' => 'Ботсвана', 'name_eng' => 'Botswana']);
        DB::table('countries')->insert(['name_ru' => 'Бразилия', 'name_eng' => 'Brazil']);
        DB::table('countries')->insert(['name_ru' => 'Британские Виргинские острова', 'name_eng' => 'British Virgin Islands']);
        DB::table('countries')->insert(['name_ru' => 'Бруней', 'name_eng' => 'Brunei']);
        DB::table('countries')->insert(['name_ru' => 'Буркина-Фасо', 'name_eng' => 'Burkina Faso']);
        DB::table('countries')->insert(['name_ru' => 'Бурунди', 'name_eng' => 'Burundi']);
        DB::table('countries')->insert(['name_ru' => 'Бутан', 'name_eng' => 'Butane']);
        DB::table('countries')->insert(['name_ru' => 'Вануату', 'name_eng' => 'Vanuatu']);
        DB::table('countries')->insert(['name_ru' => 'Ватикан', 'name_eng' => 'Vatican']);
        DB::table('countries')->insert(['name_ru' => 'Великобритания', 'name_eng' => 'United Kingdom']);
        DB::table('countries')->insert(['name_ru' => 'Венгрия', 'name_eng' => 'Hungary']);
        DB::table('countries')->insert(['name_ru' => 'Венесуэла', 'name_eng' => 'Venezuela']);
        DB::table('countries')->insert(['name_ru' => 'Восточный Тимор', 'name_eng' => 'East Timor']);
        DB::table('countries')->insert(['name_ru' => 'Вьетнам', 'name_eng' => 'Vietnam']);
        DB::table('countries')->insert(['name_ru' => 'Габон', 'name_eng' => 'Gabon']);
        DB::table('countries')->insert(['name_ru' => 'Гайана', 'name_eng' => 'Guyana']);
        DB::table('countries')->insert(['name_ru' => 'Гаити', 'name_eng' => 'Haiti']);
        DB::table('countries')->insert(['name_ru' => 'Гамбия', 'name_eng' => 'Gambia']);
        DB::table('countries')->insert(['name_ru' => 'Гана', 'name_eng' => 'Ghana']);
        DB::table('countries')->insert(['name_ru' => 'Гваделупа', 'name_eng' => 'Guadeloupe']);
        DB::table('countries')->insert(['name_ru' => 'Гватемала', 'name_eng' => 'Guatemala']);
        DB::table('countries')->insert(['name_ru' => 'Гвинея', 'name_eng' => 'Guinea']);
        DB::table('countries')->insert(['name_ru' => 'Гвинея-Бисау', 'name_eng' => 'Guinea-Bissau']);
        DB::table('countries')->insert(['name_ru' => 'Германия', 'name_eng' => 'Germany']);
        DB::table('countries')->insert(['name_ru' => 'Гибралтар', 'name_eng' => 'Gibraltar']);
        DB::table('countries')->insert(['name_ru' => 'Гондурас', 'name_eng' => 'Honduras']);
        DB::table('countries')->insert(['name_ru' => 'Гонконг', 'name_eng' => 'Hong Kong']);
        DB::table('countries')->insert(['name_ru' => 'Гренада', 'name_eng' => 'Grenada']);
        DB::table('countries')->insert(['name_ru' => 'Гренландия', 'name_eng' => 'Greenland']);
        DB::table('countries')->insert(['name_ru' => 'Греция', 'name_eng' => 'Greece']);
        DB::table('countries')->insert(['name_ru' => 'Грузия', 'name_eng' => 'Georgia']);
        DB::table('countries')->insert(['name_ru' => 'Дания', 'name_eng' => 'Denmark']);
        DB::table('countries')->insert(['name_ru' => 'Демократическая Республика Конго', 'name_eng' => 'Democratic Republic of the Congo']);
        DB::table('countries')->insert(['name_ru' => 'Джибути', 'name_eng' => 'Djibouti']);
        DB::table('countries')->insert(['name_ru' => 'Доминика', 'name_eng' => 'Dominica']);
        DB::table('countries')->insert(['name_ru' => 'Доминиканская Республика', 'name_eng' => 'Dominican Republic']);
        DB::table('countries')->insert(['name_ru' => 'Египет', 'name_eng' => 'Egypt']);
        DB::table('countries')->insert(['name_ru' => 'Замбия', 'name_eng' => 'Zambia']);
        DB::table('countries')->insert(['name_ru' => 'Западная Сахара', 'name_eng' => 'West Sahara']);
        DB::table('countries')->insert(['name_ru' => 'Зимбабве', 'name_eng' => 'Zimbabwe']);
        DB::table('countries')->insert(['name_ru' => 'Йемен', 'name_eng' => 'Yemen']);
        DB::table('countries')->insert(['name_ru' => 'Израиль', 'name_eng' => 'Israel']);
        DB::table('countries')->insert(['name_ru' => 'Индия', 'name_eng' => 'India']);
        DB::table('countries')->insert(['name_ru' => 'Индонезия', 'name_eng' => 'Indonesia']);
        DB::table('countries')->insert(['name_ru' => 'Иордания', 'name_eng' => 'Jordan']);
        DB::table('countries')->insert(['name_ru' => 'Ирак', 'name_eng' => 'Iraq']);
        DB::table('countries')->insert(['name_ru' => 'Иран', 'name_eng' => 'Iran']);
        DB::table('countries')->insert(['name_ru' => 'Ирландия', 'name_eng' => 'Ireland']);
        DB::table('countries')->insert(['name_ru' => 'Исландия', 'name_eng' => 'Iceland']);
        DB::table('countries')->insert(['name_ru' => 'Испания', 'name_eng' => 'Spain']);
        DB::table('countries')->insert(['name_ru' => 'Италия', 'name_eng' => 'Italy']);
        DB::table('countries')->insert(['name_ru' => 'Кабо-Верде', 'name_eng' => 'Cape Verde']);
        DB::table('countries')->insert(['name_ru' => 'Казахстан', 'name_eng' => 'Kazakhstan']);
        DB::table('countries')->insert(['name_ru' => 'Каймановы острова', 'name_eng' => 'Cayman islands']);
        DB::table('countries')->insert(['name_ru' => 'Камбоджа', 'name_eng' => 'Cambodia']);
        DB::table('countries')->insert(['name_ru' => 'Камерун', 'name_eng' => 'Cameroon']);
        DB::table('countries')->insert(['name_ru' => 'Канада', 'name_eng' => 'Canada']);
        DB::table('countries')->insert(['name_ru' => 'Катар', 'name_eng' => 'Qatar']);
        DB::table('countries')->insert(['name_ru' => 'Кения', 'name_eng' => 'Kenya']);
        DB::table('countries')->insert(['name_ru' => 'Кипр', 'name_eng' => 'Cyprus']);
        DB::table('countries')->insert(['name_ru' => 'Киргизия', 'name_eng' => 'Kyrgyzstan']);
        DB::table('countries')->insert(['name_ru' => 'Кирибати', 'name_eng' => 'Kiribati']);
        DB::table('countries')->insert(['name_ru' => 'Китай', 'name_eng' => 'China']);
        DB::table('countries')->insert(['name_ru' => 'Колумбия', 'name_eng' => 'Colombia']);
        DB::table('countries')->insert(['name_ru' => 'Коморские острова', 'name_eng' => 'Comoros']);
        DB::table('countries')->insert(['name_ru' => 'Коста-Рика', 'name_eng' => 'Costa Rica']);
        DB::table('countries')->insert(['name_ru' => 'Кот-д’Ивуар', 'name_eng' => 'Ivory Coast']);
        DB::table('countries')->insert(['name_ru' => 'Куба', 'name_eng' => 'Cuba']);
        DB::table('countries')->insert(['name_ru' => 'Кувейт', 'name_eng' => 'Kuwait']);
        DB::table('countries')->insert(['name_ru' => 'Лаос', 'name_eng' => 'Laos']);
        DB::table('countries')->insert(['name_ru' => 'Латвия', 'name_eng' => 'Latvia	']);
        DB::table('countries')->insert(['name_ru' => 'Лесото', 'name_eng' => 'Lesotho']);
        DB::table('countries')->insert(['name_ru' => 'Либерия', 'name_eng' => 'Liberia']);
        DB::table('countries')->insert(['name_ru' => 'Ливан', 'name_eng' => 'Lebanon']);
        DB::table('countries')->insert(['name_ru' => 'Ливия', 'name_eng' => 'Libya']);
        DB::table('countries')->insert(['name_ru' => 'Литва', 'name_eng' => 'Lithuania']);
        DB::table('countries')->insert(['name_ru' => 'Лихтенштейн', 'name_eng' => 'Liechtenstein']);
        DB::table('countries')->insert(['name_ru' => 'Люксембург', 'name_eng' => 'Luxembourg']);
        DB::table('countries')->insert(['name_ru' => 'Маврикий', 'name_eng' => 'Mauritius']);
        DB::table('countries')->insert(['name_ru' => 'Мавритания', 'name_eng' => 'Mauritania']);
        DB::table('countries')->insert(['name_ru' => 'Мадагаскар', 'name_eng' => 'Madagascar']);
        DB::table('countries')->insert(['name_ru' => 'Майотта', 'name_eng' => 'Mayotte']);
        DB::table('countries')->insert(['name_ru' => 'Макао', 'name_eng' => 'Macau']);
        DB::table('countries')->insert(['name_ru' => 'Македония', 'name_eng' => 'Macedonia']);
        DB::table('countries')->insert(['name_ru' => 'Малави', 'name_eng' => 'Malawi']);
        DB::table('countries')->insert(['name_ru' => 'Малайзия', 'name_eng' => 'Malaysia']);
        DB::table('countries')->insert(['name_ru' => 'Мали', 'name_eng' => 'Mali']);
        DB::table('countries')->insert(['name_ru' => 'Мальдивы', 'name_eng' => 'Maldives']);
        DB::table('countries')->insert(['name_ru' => 'Мальта', 'name_eng' => 'Malta']);
        DB::table('countries')->insert(['name_ru' => 'Марокко', 'name_eng' => 'Morocco']);
        DB::table('countries')->insert(['name_ru' => 'Маршалловы острова', 'name_eng' => 'Marshall Islands']);
        DB::table('countries')->insert(['name_ru' => 'Мексика', 'name_eng' => 'Marshall Islands']);
        DB::table('countries')->insert(['name_ru' => 'Мозамбик', 'name_eng' => 'Mozambique']);
        DB::table('countries')->insert(['name_ru' => 'Молдова', 'name_eng' => 'Moldova']);
        DB::table('countries')->insert(['name_ru' => 'Монако', 'name_eng' => 'Monaco']);
        DB::table('countries')->insert(['name_ru' => 'Монголия', 'name_eng' => 'Mongolia']);
        DB::table('countries')->insert(['name_ru' => 'Мьянма', 'name_eng' => 'Myanmar']);
        DB::table('countries')->insert(['name_ru' => 'Намибия', 'name_eng' => 'Namibia']);
        DB::table('countries')->insert(['name_ru' => 'Науру', 'name_eng' => 'Nauru']);
        DB::table('countries')->insert(['name_ru' => 'Непал', 'name_eng' => 'Nepal']);
        DB::table('countries')->insert(['name_ru' => 'Нигер', 'name_eng' => 'Niger']);
        DB::table('countries')->insert(['name_ru' => 'Нигерия', 'name_eng' => 'Nigeria']);
        DB::table('countries')->insert(['name_ru' => 'Нидерланды', 'name_eng' => 'Netherlands']);
        DB::table('countries')->insert(['name_ru' => 'Никарагуа', 'name_eng' => 'Nicaragua']);
        DB::table('countries')->insert(['name_ru' => 'Новая Зеландия', 'name_eng' => 'New Zealand']);
        DB::table('countries')->insert(['name_ru' => 'Новая Каледония', 'name_eng' => 'New Caledonia']);
        DB::table('countries')->insert(['name_ru' => 'Норвегия', 'name_eng' => 'Norway']);
        DB::table('countries')->insert(['name_ru' => 'Объединённые Арабские Эмираты', 'name_eng' => 'United Arab Emirates']);
        DB::table('countries')->insert(['name_ru' => 'Оман', 'name_eng' => 'Oman']);
        DB::table('countries')->insert(['name_ru' => 'Острова Кука', 'name_eng' => 'Cook islands']);
        DB::table('countries')->insert(['name_ru' => 'Пакистан', 'name_eng' => 'Pakistan']);
        DB::table('countries')->insert(['name_ru' => 'Палау', 'name_eng' => 'Palau']);
        DB::table('countries')->insert(['name_ru' => 'Панама', 'name_eng' => 'Panama']);
        DB::table('countries')->insert(['name_ru' => 'Папуа - Новая Гвинея', 'name_eng' => 'Papua New Guinea']);
        DB::table('countries')->insert(['name_ru' => 'Парагвай', 'name_eng' => 'Paraguay']);
        DB::table('countries')->insert(['name_ru' => 'Перу', 'name_eng' => 'Peru']);
        DB::table('countries')->insert(['name_ru' => 'Польша', 'name_eng' => 'Poland']);
        DB::table('countries')->insert(['name_ru' => 'Португалия', 'name_eng' => 'Portugal']);
        DB::table('countries')->insert(['name_ru' => 'Республика Конго', 'name_eng' => 'Republic of the Congo']);
        DB::table('countries')->insert(['name_ru' => 'Реюньон', 'name_eng' => 'Reunion']);
        DB::table('countries')->insert(['name_ru' => 'Россия', 'name_eng' => 'Russia']);
        DB::table('countries')->insert(['name_ru' => 'Руанда', 'name_eng' => 'Rwanda']);
        DB::table('countries')->insert(['name_ru' => 'Румыния', 'name_eng' => 'Romania']);
        DB::table('countries')->insert(['name_ru' => 'Самоа', 'name_eng' => 'Samoa']);
        DB::table('countries')->insert(['name_ru' => 'Сан-Марино', 'name_eng' => 'San marino']);
        DB::table('countries')->insert(['name_ru' => 'Сан-Томе и Принсипи', 'name_eng' => 'Sao Tome and Principe']);
        DB::table('countries')->insert(['name_ru' => 'Саудовская Аравия', 'name_eng' => 'Saudi Arabia']);
        DB::table('countries')->insert(['name_ru' => 'Северная Корея', 'name_eng' => 'North Korea']);
        DB::table('countries')->insert(['name_ru' => 'Сейшельские острова', 'name_eng' => 'Seychelles']);
        DB::table('countries')->insert(['name_ru' => 'Сенегал', 'name_eng' => 'Senegal']);
        DB::table('countries')->insert(['name_ru' => 'Сент-Винсент и Гренадины', 'name_eng' => 'Saint Vincent and the Grenadines']);
        DB::table('countries')->insert(['name_ru' => 'Сент-Китс и Невис', 'name_eng' => 'Saint Kitts and Nevis']);
        DB::table('countries')->insert(['name_ru' => 'Сент-Люсия', 'name_eng' => 'Saint Lucia']);
        DB::table('countries')->insert(['name_ru' => 'Сербия', 'name_eng' => 'Serbia']);
        DB::table('countries')->insert(['name_ru' => 'Сингапур', 'name_eng' => 'Singapore']);
        DB::table('countries')->insert(['name_ru' => 'Сирия', 'name_eng' => 'Syria']);
        DB::table('countries')->insert(['name_ru' => 'Словакия', 'name_eng' => 'Slovakia']);
        DB::table('countries')->insert(['name_ru' => 'Словения', 'name_eng' => 'Slovenia']);
        DB::table('countries')->insert(['name_ru' => 'Сомали', 'name_eng' => 'Somalia']);
        DB::table('countries')->insert(['name_ru' => 'Судан', 'name_eng' => 'Sudan']);
        DB::table('countries')->insert(['name_ru' => 'Суринам', 'name_eng' => 'Suriname']);
        DB::table('countries')->insert(['name_ru' => 'США', 'name_eng' => 'USA']);
        DB::table('countries')->insert(['name_ru' => 'Сьерра-Леоне', 'name_eng' => 'Sierra Leone']);
        DB::table('countries')->insert(['name_ru' => 'Таджикистан', 'name_eng' => 'Tajikistan']);
        DB::table('countries')->insert(['name_ru' => 'Таиланд', 'name_eng' => 'Thailand']);
        DB::table('countries')->insert(['name_ru' => 'Танзания', 'name_eng' => 'Thailand']);
        DB::table('countries')->insert(['name_ru' => 'Тёркс и Кайкос', 'name_eng' => 'Turks and Caicos']);
        DB::table('countries')->insert(['name_ru' => 'Того', 'name_eng' => 'Togo']);
        DB::table('countries')->insert(['name_ru' => 'Тонга', 'name_eng' => 'Tonga']);
        DB::table('countries')->insert(['name_ru' => 'Тринидад и Тобаго', 'name_eng' => 'Trinidad and Tobago']);
        DB::table('countries')->insert(['name_ru' => 'Тувалу', 'name_eng' => 'Trinidad and Tobago']);
        DB::table('countries')->insert(['name_ru' => 'Тунис', 'name_eng' => 'Tunisia']);
        DB::table('countries')->insert(['name_ru' => 'Туркменистан', 'name_eng' => 'Tunisia']);
        DB::table('countries')->insert(['name_ru' => 'Турция', 'name_eng' => 'Turkey']);
        DB::table('countries')->insert(['name_ru' => 'Уганда', 'name_eng' => 'Uganda']);
        DB::table('countries')->insert(['name_ru' => 'Узбекистан', 'name_eng' => 'Uzbekistan']);
        DB::table('countries')->insert(['name_ru' => 'Украина', 'name_eng' => 'Ukraine']);
        DB::table('countries')->insert(['name_ru' => 'Уругвай', 'name_eng' => 'Uruguay']);
        DB::table('countries')->insert(['name_ru' => 'Федеративные Штаты Микронезии', 'name_eng' => 'Federated States of Micronesia']);
        DB::table('countries')->insert(['name_ru' => 'Фиджи', 'name_eng' => 'Fiji']);
        DB::table('countries')->insert(['name_ru' => 'Филиппины', 'name_eng' => 'Philippines']);
        DB::table('countries')->insert(['name_ru' => 'Финляндия', 'name_eng' => 'Finland']);
        DB::table('countries')->insert(['name_ru' => 'Франция', 'name_eng' => 'France']);
        DB::table('countries')->insert(['name_ru' => 'Хорватия', 'name_eng' => 'Croatia']);
        DB::table('countries')->insert(['name_ru' => 'Центрально-Африканская Республика', 'name_eng' => 'Central African Republic']);
        DB::table('countries')->insert(['name_ru' => 'Чад', 'name_eng' => 'Chad']);
        DB::table('countries')->insert(['name_ru' => 'Черногория', 'name_eng' => 'Montenegro']);
        DB::table('countries')->insert(['name_ru' => 'Чехия', 'name_eng' => 'Czech']);
        DB::table('countries')->insert(['name_ru' => 'Чили', 'name_eng' => 'Chile']);
        DB::table('countries')->insert(['name_ru' => 'Швейцария', 'name_eng' => 'Switzerland']);
        DB::table('countries')->insert(['name_ru' => 'Швеция', 'name_eng' => 'Sweden']);
        DB::table('countries')->insert(['name_ru' => 'Шри-Ланка', 'name_eng' => 'Sri Lanka']);
        DB::table('countries')->insert(['name_ru' => 'Эквадор', 'name_eng' => 'Ecuador']);
        DB::table('countries')->insert(['name_ru' => 'Экваториальная Гвинея', 'name_eng' => 'Equatorial Guinea']);
        DB::table('countries')->insert(['name_ru' => 'Эритрея', 'name_eng' => 'Eritrea']);
        DB::table('countries')->insert(['name_ru' => 'Эстония', 'name_eng' => 'Estonia']);
        DB::table('countries')->insert(['name_ru' => 'Эфиопия', 'name_eng' => 'Ethiopia']);
        DB::table('countries')->insert(['name_ru' => 'ЮАР', 'name_eng' => 'South Africa']);
        DB::table('countries')->insert(['name_ru' => 'Южная Корея', 'name_eng' => 'South Korea']);
        DB::table('countries')->insert(['name_ru' => 'Ямайка', 'name_eng' => 'Jamaica']);
        DB::table('countries')->insert(['name_ru' => 'Япония', 'name_eng' => 'Japan']);
    }
}
